/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.estacionamientoproyecto;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author dxnie
 */
public class visualizarContenido extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(visualizarContenido.class.getName());

    /**
     * Creates new form visualizarContenido
     */
    public visualizarContenido() {
        initComponents();
        
        //ocultar
    PanelLogin.setVisible(true);
    PanelFunciones.setVisible(false);
    JpanelAñadirUsuario.setVisible(false);
    PanelIngresarDatos.setVisible(false);
    TxtEspera.setVisible(false);
    BarraTiempo.setVisible(false);
        TxtTiempoI.setVisible(false);
            TiempoVariable.setVisible(false);
         setSize(850,630);
         setResizable(false);
         
          setLocationRelativeTo(null);
          // --- CENTRAR PANEL ---
centrarPanel(PanelLogin);
centrarPanel(PanelIngresarDatos);

// Recentrar al redimensionar la ventana
addComponentListener(new java.awt.event.ComponentAdapter() {
    @Override
    public void componentResized(java.awt.event.ComponentEvent evt) {
        centrarPanel(PanelLogin);
    centrarPanel(PanelFunciones);
    centrarPanel(PanelIngresarDatos);
    }
});
    }

    
    
    
    
    
    
    
    private void centrarPanel(JPanel panel) {
    int x = (getWidth() - panel.getWidth()) / 2;
    int y = (getHeight() - panel.getHeight()) / 2;
    panel.setLocation(x, y);
}
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtGrupoLogin = new javax.swing.ButtonGroup();
        ButtonGroupIngresar = new javax.swing.ButtonGroup();
        ButGroupFunciones = new javax.swing.ButtonGroup();
        FormatoTiempo = new javax.swing.ButtonGroup();
        grupoTipoAutoingresado = new javax.swing.ButtonGroup();
        PanelLogin = new javax.swing.JPanel();
        bienvenida = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SelecAdmin = new javax.swing.JRadioButton();
        SelectEmpleado = new javax.swing.JRadioButton();
        LoginUsuario = new javax.swing.JLabel();
        UsuarioIngresado = new javax.swing.JTextField();
        loginContra = new javax.swing.JLabel();
        ContraIngresada = new javax.swing.JPasswordField();
        IniciarSesion = new javax.swing.JButton();
        TxtEspera = new javax.swing.JLabel();
        BarraTiempo = new javax.swing.JProgressBar();
        butSalir = new javax.swing.JButton();
        PanelFunciones = new javax.swing.JPanel();
        ButIngresar = new javax.swing.JToggleButton();
        ButDisponibilidad = new javax.swing.JToggleButton();
        ButEliminar = new javax.swing.JToggleButton();
        ButModificar = new javax.swing.JToggleButton();
        ButFinancias = new javax.swing.JToggleButton();
        PanelIngresarDatos = new javax.swing.JPanel();
        NoPlaca = new javax.swing.JLabel();
        ingresaPlaca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ButFlat = new javax.swing.JRadioButton();
        ButVariable = new javax.swing.JRadioButton();
        BuscarDbPlaca = new javax.swing.JButton();
        aviso = new javax.swing.JLabel();
        TxtTiempoI = new javax.swing.JLabel();
        TiempoVariable = new javax.swing.JTextField();
        generarImpresion = new javax.swing.JButton();
        autoautoingresado = new javax.swing.JRadioButton();
        motoautoingresado = new javax.swing.JRadioButton();
        JpanelAñadirUsuario = new javax.swing.JPanel();
        NombreIngresar = new javax.swing.JLabel();
        CarnetIngresar = new javax.swing.JLabel();
        PlacaIngresar = new javax.swing.JLabel();
        IngresarNombre = new javax.swing.JTextField();
        IngresarCarnet = new javax.swing.JTextField();
        IngresarPlaca = new javax.swing.JTextField();
        ButMoto = new javax.swing.JRadioButton();
        ButAuto = new javax.swing.JRadioButton();
        AgregarNuevoUsuario = new javax.swing.JButton();
        Puesto = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        bienvenida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenida.setText("Bienvenido");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Inicie sesión:");

        ButtGrupoLogin.add(SelecAdmin);
        SelecAdmin.setText("Administrador");

        ButtGrupoLogin.add(SelectEmpleado);
        SelectEmpleado.setText("Empleado");

        LoginUsuario.setText("Usuario:");

        loginContra.setText("Contraseña:");

        ContraIngresada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraIngresadaActionPerformed(evt);
            }
        });

        IniciarSesion.setText("Iniciar sesion");
        IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionActionPerformed(evt);
            }
        });

        TxtEspera.setText("TIempo de espera :");
        TxtEspera.setName(""); // NOI18N

        butSalir.setText("Salir");
        butSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelLoginLayout = new javax.swing.GroupLayout(PanelLogin);
        PanelLogin.setLayout(PanelLoginLayout);
        PanelLoginLayout.setHorizontalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(SelecAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(SelectEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLoginLayout.createSequentialGroup()
                                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLoginLayout.createSequentialGroup()
                                        .addGap(277, 277, 277)
                                        .addComponent(LoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelLoginLayout.createSequentialGroup()
                                        .addGap(268, 268, 268)
                                        .addComponent(loginContra, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLoginLayout.createSequentialGroup()
                                .addComponent(TxtEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)))
                        .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BarraTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelLoginLayout.createSequentialGroup()
                                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ContraIngresada, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UsuarioIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(IniciarSesion))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLoginLayout.createSequentialGroup()
                                .addComponent(butSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(136, 136, 136)))))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        PanelLoginLayout.setVerticalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectEmpleado)
                    .addComponent(SelecAdmin))
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LoginUsuario)
                            .addComponent(UsuarioIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loginContra)
                            .addComponent(ContraIngresada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(IniciarSesion)))
                .addGap(28, 28, 28)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BarraTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(butSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        ButGroupFunciones.add(ButIngresar);
        ButIngresar.setText("Ingresar");
        ButIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButIngresarActionPerformed(evt);
            }
        });

        ButGroupFunciones.add(ButDisponibilidad);
        ButDisponibilidad.setText("Disponibilidad");
        ButDisponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButDisponibilidadActionPerformed(evt);
            }
        });

        ButGroupFunciones.add(ButEliminar);
        ButEliminar.setText("Eliminar");
        ButEliminar.setAutoscrolls(true);

        ButGroupFunciones.add(ButModificar);
        ButModificar.setText("Modificar");
        ButModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButModificarActionPerformed(evt);
            }
        });

        ButGroupFunciones.add(ButFinancias);
        ButFinancias.setText("Financias");

        PanelIngresarDatos.setAutoscrolls(true);

        NoPlaca.setText("Placa:");

        jLabel1.setText("Tipo");

        FormatoTiempo.add(ButFlat);
        ButFlat.setText("Plano");
        ButFlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButFlatActionPerformed(evt);
            }
        });

        FormatoTiempo.add(ButVariable);
        ButVariable.setText("Variable");
        ButVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButVariableActionPerformed(evt);
            }
        });

        BuscarDbPlaca.setText("Verificar");
        BuscarDbPlaca.setActionCommand("");
        BuscarDbPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarDbPlacaActionPerformed(evt);
            }
        });

        aviso.setText(" ");

        TxtTiempoI.setText("Tiempo");

        TiempoVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiempoVariableActionPerformed(evt);
            }
        });

        generarImpresion.setText("Ticket");
        generarImpresion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarImpresionActionPerformed(evt);
            }
        });

        grupoTipoAutoingresado.add(autoautoingresado);
        autoautoingresado.setText("auto");
        autoautoingresado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoautoingresadoActionPerformed(evt);
            }
        });

        grupoTipoAutoingresado.add(motoautoingresado);
        motoautoingresado.setText("moto");
        motoautoingresado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motoautoingresadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelIngresarDatosLayout = new javax.swing.GroupLayout(PanelIngresarDatos);
        PanelIngresarDatos.setLayout(PanelIngresarDatosLayout);
        PanelIngresarDatosLayout.setHorizontalGroup(
            PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTiempoI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoPlaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                        .addComponent(ingresaPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(BuscarDbPlaca))
                    .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                        .addComponent(ButFlat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                        .addComponent(autoautoingresado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(motoautoingresado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                        .addComponent(TiempoVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(generarImpresion)))
                .addGap(0, 341, Short.MAX_VALUE))
        );
        PanelIngresarDatosLayout.setVerticalGroup(
            PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresaPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarDbPlaca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autoautoingresado)
                    .addComponent(motoautoingresado))
                .addGap(19, 19, 19)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButFlat)
                    .addComponent(ButVariable))
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TiempoVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtTiempoI)))
                    .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(generarImpresion)))
                .addGap(323, 323, 323))
        );

        NombreIngresar.setText("Nombre:");

        CarnetIngresar.setText("Carnet:");

        PlacaIngresar.setText("Placa:");

        ButtonGroupIngresar.add(ButMoto);
        ButMoto.setText("Motocicleta");
        ButMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButMotoActionPerformed(evt);
            }
        });

        ButtonGroupIngresar.add(ButAuto);
        ButAuto.setText("Automovil");

        AgregarNuevoUsuario.setText("Guardar");
        AgregarNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarNuevoUsuarioActionPerformed(evt);
            }
        });

        Puesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESTUDIANTE", "CATEDRATICO" }));

        javax.swing.GroupLayout JpanelAñadirUsuarioLayout = new javax.swing.GroupLayout(JpanelAñadirUsuario);
        JpanelAñadirUsuario.setLayout(JpanelAñadirUsuarioLayout);
        JpanelAñadirUsuarioLayout.setHorizontalGroup(
            JpanelAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelAñadirUsuarioLayout.createSequentialGroup()
                .addGroup(JpanelAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelAñadirUsuarioLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(JpanelAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpanelAñadirUsuarioLayout.createSequentialGroup()
                                .addComponent(ButAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JpanelAñadirUsuarioLayout.createSequentialGroup()
                                .addGroup(JpanelAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NombreIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CarnetIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PlacaIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(JpanelAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(IngresarNombre)
                                    .addComponent(IngresarCarnet)
                                    .addComponent(IngresarPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))))
                    .addGroup(JpanelAñadirUsuarioLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(AgregarNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        JpanelAñadirUsuarioLayout.setVerticalGroup(
            JpanelAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelAñadirUsuarioLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(JpanelAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreIngresar)
                    .addComponent(IngresarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(JpanelAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CarnetIngresar)
                    .addComponent(IngresarCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(JpanelAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlacaIngresar)
                    .addComponent(IngresarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(JpanelAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButMoto)
                    .addComponent(ButAuto)
                    .addComponent(Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AgregarNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelFuncionesLayout = new javax.swing.GroupLayout(PanelFunciones);
        PanelFunciones.setLayout(PanelFuncionesLayout);
        PanelFuncionesLayout.setHorizontalGroup(
            PanelFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFuncionesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButFinancias, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
            .addGroup(PanelFuncionesLayout.createSequentialGroup()
                .addGroup(PanelFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFuncionesLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(PanelIngresarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFuncionesLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(JpanelAñadirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelFuncionesLayout.setVerticalGroup(
            PanelFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFuncionesLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(PanelFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButFinancias)
                    .addComponent(ButModificar)
                    .addComponent(ButEliminar)
                    .addComponent(ButDisponibilidad)
                    .addComponent(ButIngresar))
                .addGap(44, 44, 44)
                .addComponent(PanelIngresarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpanelAñadirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(PanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(PanelFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(638, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 296, Short.MAX_VALUE)
                .addComponent(PanelFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(376, 376, 376))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContraIngresadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraIngresadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraIngresadaActionPerformed

    private void IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionActionPerformed

        
        String Usuario=UsuarioIngresado.getText();
        char[] contraseña=ContraIngresada.getPassword();
       
        VerificarContraseña VC=new VerificarContraseña(Usuario,contraseña,PanelFunciones, PanelLogin, UsuarioIngresado, ContraIngresada, IniciarSesion, TxtEspera, BarraTiempo,ButtGrupoLogin,JpanelAñadirUsuario);
       
      
        VC.verificar();
        
       
    }//GEN-LAST:event_IniciarSesionActionPerformed

    private void butSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butSalirMouseClicked
      ImageIcon icono= new ImageIcon(getClass().getResource("/Imagenes/Salir.jpg"));
        butSalir.addActionListener((ActionEvent e)->{
            
         int opcion=JOptionPane.showConfirmDialog(this,"Esta seguro de salir?","Salir",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, icono);
            if(opcion!=1){
            
            System.exit(0);
        }
                   
            
        });
        
        
        
    }//GEN-LAST:event_butSalirMouseClicked

    private void ButModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButModificarActionPerformed
        
        
       
        
           if( ButModificar.isSelected()){
               PanelIngresarDatos.setVisible(true);
               

    }//GEN-LAST:event_ButModificarActionPerformed
    }
    private void ButDisponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButDisponibilidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButDisponibilidadActionPerformed

    private void ButIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButIngresarActionPerformed
        
        
       
        
        
        
        
        
    }//GEN-LAST:event_ButIngresarActionPerformed

    private void ButMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButMotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButMotoActionPerformed

    private void AgregarNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarNuevoUsuarioActionPerformed
     
        //obteniendo datos
       String Nombre=IngresarNombre.getText();
       int Carnet=Integer.parseInt(IngresarCarnet.getText());
       String Placa=IngresarPlaca.getText(); 
      String Tipo;
       if(ButAuto.isSelected()){
          
          Tipo="automovil";
      } else{
           Tipo="moto";
           
       }
       
       String area="";
       
       if(Puesto.getSelectedItem().equals("CATEDRATICO")){
           
           area="CATEDRATICO";
           
       }else if(Puesto.getSelectedItem().equals("ESTUDIANTE")){
           
           
           area="ESTUDIANTE";
       }else{
           JOptionPane.showMessageDialog(null,"Ingrese un cargo","CAMPO VACIO",JOptionPane.INFORMATION_MESSAGE);
           
       }
       
         //accion al seleccionar guradar
         
         
         Vehiculo V=new Vehiculo(Placa,Tipo,area);  
         
         Usuario us=new Usuario(0,Nombre,Carnet,V);  
           
        UsuarioDB agg= new UsuarioDB();
        
        agg.AgregarDb(us,V);
        
   
        
        ingresaPlaca.setText(V.getPlaca());
        IngresarNombre.setText("");
        IngresarCarnet.setText("");
        IngresarPlaca.setText("");
          JpanelAñadirUsuario.setVisible(false);
            PanelIngresarDatos.setVisible(true);
            
            Vehiculo Encontrado=agg.BuscarPorPlaca(ingresaPlaca.getText());
            if(Encontrado!=null){
             
             aviso.setText("Usuario encontrado Prosiga");
              String modelo = Encontrado.getTipo();
         
         
         
        if(modelo.equalsIgnoreCase("automovil")){
            
           autoautoingresado.setSelected(true);
            
        }else if(modelo.equalsIgnoreCase("moto")){
            
            motoautoingresado.setSelected(true);
        }}else{
             
            JpanelAñadirUsuario.setVisible(true);
            PanelIngresarDatos.setVisible(false);
             JOptionPane.showMessageDialog(null,"Usuario no Hallado","INGRESE USUARIO",JOptionPane.INFORMATION_MESSAGE);
         }


    }//GEN-LAST:event_AgregarNuevoUsuarioActionPerformed

    private void ButFlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButFlatActionPerformed

        
        
        
        
        
    }//GEN-LAST:event_ButFlatActionPerformed

    private void BuscarDbPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarDbPlacaActionPerformed
        
        
        
         UsuarioDB us= new UsuarioDB();
         
         Vehiculo Encontrado=us.BuscarPorPlaca(ingresaPlaca.getText());
         
         if(Encontrado!=null){
             
             aviso.setText("Usuario encontrado Prosiga");
              String modelo = Encontrado.getTipo();
         
         
         
        if(modelo.equalsIgnoreCase("automovil")){
            
           autoautoingresado.setSelected(true);
            
        }else if(modelo.equalsIgnoreCase("moto")){
            
            motoautoingresado.setSelected(true);
        }}else{
             
            JpanelAñadirUsuario.setVisible(true);
            PanelIngresarDatos.setVisible(false);
             JOptionPane.showMessageDialog(null,"Usuario no Hallado","INGRESE USUARIO",JOptionPane.INFORMATION_MESSAGE);
         }
         
         
         
      
         
         
         
         
    }//GEN-LAST:event_BuscarDbPlacaActionPerformed

    private void ButVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButVariableActionPerformed
       
        if(ButVariable.isSelected()){
            TxtTiempoI.setVisible(true);
            TiempoVariable.setVisible(true);
     
        }
        
        
        
        
    }//GEN-LAST:event_ButVariableActionPerformed

    private void TiempoVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiempoVariableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TiempoVariableActionPerformed

    private void autoautoingresadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoautoingresadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoautoingresadoActionPerformed

    private void motoautoingresadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motoautoingresadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motoautoingresadoActionPerformed

    private void generarImpresionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarImpresionActionPerformed

        
        
        UsuarioDB us=new UsuarioDB();

        
     
    }//GEN-LAST:event_generarImpresionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        
        java.awt.EventQueue.invokeLater(() -> new visualizarContenido().setVisible(true));
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarNuevoUsuario;
    private javax.swing.JProgressBar BarraTiempo;
    private javax.swing.JButton BuscarDbPlaca;
    private javax.swing.JRadioButton ButAuto;
    private javax.swing.JToggleButton ButDisponibilidad;
    private javax.swing.JToggleButton ButEliminar;
    private javax.swing.JToggleButton ButFinancias;
    private javax.swing.JRadioButton ButFlat;
    private javax.swing.ButtonGroup ButGroupFunciones;
    private javax.swing.JToggleButton ButIngresar;
    private javax.swing.JToggleButton ButModificar;
    private javax.swing.JRadioButton ButMoto;
    private javax.swing.JRadioButton ButVariable;
    private javax.swing.ButtonGroup ButtGrupoLogin;
    private javax.swing.ButtonGroup ButtonGroupIngresar;
    private javax.swing.JLabel CarnetIngresar;
    private javax.swing.JPasswordField ContraIngresada;
    private javax.swing.ButtonGroup FormatoTiempo;
    private javax.swing.JTextField IngresarCarnet;
    private javax.swing.JTextField IngresarNombre;
    private javax.swing.JTextField IngresarPlaca;
    private javax.swing.JButton IniciarSesion;
    private javax.swing.JPanel JpanelAñadirUsuario;
    private javax.swing.JLabel LoginUsuario;
    private javax.swing.JLabel NoPlaca;
    private javax.swing.JLabel NombreIngresar;
    private javax.swing.JPanel PanelFunciones;
    private javax.swing.JPanel PanelIngresarDatos;
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JLabel PlacaIngresar;
    private javax.swing.JComboBox<String> Puesto;
    private javax.swing.JRadioButton SelecAdmin;
    private javax.swing.JRadioButton SelectEmpleado;
    private javax.swing.JTextField TiempoVariable;
    private javax.swing.JLabel TxtEspera;
    private javax.swing.JLabel TxtTiempoI;
    private javax.swing.JTextField UsuarioIngresado;
    private javax.swing.JRadioButton autoautoingresado;
    private javax.swing.JLabel aviso;
    private javax.swing.JLabel bienvenida;
    private javax.swing.JButton butSalir;
    private javax.swing.JButton generarImpresion;
    private javax.swing.ButtonGroup grupoTipoAutoingresado;
    private javax.swing.JTextField ingresaPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel loginContra;
    private javax.swing.JRadioButton motoautoingresado;
    // End of variables declaration//GEN-END:variables
}
