/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.estacionamientoproyecto;

import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.awt.event.ActionEvent;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author dxnie
 */
public class visualizarContenido extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(visualizarContenido.class.getName());

    /**
     * Creates new form visualizarContenido
     */
    public visualizarContenido() {
        initComponents();
        
        
        
        
        
        
        
        
        
        
        
        //ocultar
        UsuarioDB us=new UsuarioDB();
      
        MostrarGanancias.setText(us.DatosDeldia());
        pestañas.setVisible(false);

       
        
    PanelLogin.setVisible(true);
    PanelFunciones.setVisible(false);
    
    TxtEspera.setVisible(false);
    BarraTiempo.setVisible(false);
        TxtTiempoI.setVisible(false);
            TiempoVariable.setVisible(false);
         setSize(850,630);
         setResizable(false);
         PanelREINGRESO.setVisible(false);
          setLocationRelativeTo(null);
          // --- CENTRAR PANEL ---
centrarPanel(PanelLogin);
centrarPanel(PanelIngresarDatos);

// Recentrar al redimensionar la ventana
addComponentListener(new java.awt.event.ComponentAdapter() {
    @Override
    public void componentResized(java.awt.event.ComponentEvent evt) {
        centrarPanel(PanelLogin);
    centrarPanel(PanelFunciones);
    centrarPanel(PanelIngresarDatos);
    centrarPanel(PanelREINGRESO);
    }
});
    }

    
    
    
    
    
    
    
    private void centrarPanel(JPanel panel) {
    int x = (getWidth() - panel.getWidth()) / 2;
    int y = (getHeight() - panel.getHeight()) / 2;
    panel.setLocation(x, y);
}
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtGrupoLogin = new javax.swing.ButtonGroup();
        ButtonGroupIngresar = new javax.swing.ButtonGroup();
        ButGroupFunciones = new javax.swing.ButtonGroup();
        FormatoTiempo = new javax.swing.ButtonGroup();
        grupoTipoAutoingresado = new javax.swing.ButtonGroup();
        ButonGroupOpciones = new javax.swing.ButtonGroup();
        PanelLogin = new javax.swing.JPanel();
        bienvenida = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SelecAdmin = new javax.swing.JRadioButton();
        SelectEmpleado = new javax.swing.JRadioButton();
        LoginUsuario = new javax.swing.JLabel();
        UsuarioIngresado = new javax.swing.JTextField();
        loginContra = new javax.swing.JLabel();
        ContraIngresada = new javax.swing.JPasswordField();
        IniciarSesion = new javax.swing.JButton();
        TxtEspera = new javax.swing.JLabel();
        BarraTiempo = new javax.swing.JProgressBar();
        butSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pestañas = new javax.swing.JTabbedPane();
        PanelFunciones = new javax.swing.JPanel();
        PanelIngresarDatos = new javax.swing.JPanel();
        NoPlaca = new javax.swing.JLabel();
        ingresaPlaca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ButFlat = new javax.swing.JRadioButton();
        ButVariable = new javax.swing.JRadioButton();
        BuscarDbPlaca = new javax.swing.JButton();
        aviso = new javax.swing.JLabel();
        TxtTiempoI = new javax.swing.JLabel();
        TiempoVariable = new javax.swing.JTextField();
        generarImpresion = new javax.swing.JButton();
        autoautoingresado = new javax.swing.JRadioButton();
        motoautoingresado = new javax.swing.JRadioButton();
        Pago = new javax.swing.JComboBox<>();
        txtpago = new javax.swing.JLabel();
        BilleteIngresado = new javax.swing.JTextField();
        PuestoBuscandoPlaca = new javax.swing.JComboBox<>();
        PanelReingreso = new javax.swing.JButton();
        JpanelAñadirUsuario = new javax.swing.JPanel();
        NombreIngresar = new javax.swing.JLabel();
        CarnetIngresar = new javax.swing.JLabel();
        PlacaIngresar = new javax.swing.JLabel();
        IngresarNombre = new javax.swing.JTextField();
        IngresarCarnet = new javax.swing.JTextField();
        IngresarPlaca = new javax.swing.JTextField();
        ButMoto = new javax.swing.JRadioButton();
        ButAuto = new javax.swing.JRadioButton();
        AgregarNuevoUsuario = new javax.swing.JButton();
        Puesto = new javax.swing.JComboBox<>();
        buttRegresar = new javax.swing.JButton();
        PanelREINGRESO = new javax.swing.JPanel();
        TxtReingreso = new javax.swing.JLabel();
        Reingreso = new javax.swing.JTextField();
        ButReingreso = new javax.swing.JButton();
        JpaneSalida = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        SalidaTickeID = new javax.swing.JLabel();
        RecibirTickeid = new javax.swing.JTextField();
        BuscarTIckeID = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaParaVisualizar = new javax.swing.JTable();
        CopiaInfo = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();
        MostrarGanancias = new javax.swing.JLabel();
        verT = new javax.swing.JComboBox<>();
        busquedayrescatexd = new javax.swing.JTextField();
        buscarw = new javax.swing.JButton();
        Exportar = new javax.swing.JButton();
        Mapa = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Direccioncsv = new javax.swing.JTextField();
        Seleccionar = new javax.swing.JButton();
        EleccionSubirDatos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        bienvenida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenida.setText("Bienvenido");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Inicie sesión:");

        ButtGrupoLogin.add(SelecAdmin);
        SelecAdmin.setText("Administrador");

        ButtGrupoLogin.add(SelectEmpleado);
        SelectEmpleado.setText("Empleado");

        LoginUsuario.setText("Usuario:");

        loginContra.setText("Contraseña:");

        ContraIngresada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraIngresadaActionPerformed(evt);
            }
        });

        IniciarSesion.setText("Iniciar sesion");
        IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionActionPerformed(evt);
            }
        });

        TxtEspera.setText("TIempo de espera :");
        TxtEspera.setName(""); // NOI18N

        butSalir.setText("Salir");
        butSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butSalirMouseClicked(evt);
            }
        });
        butSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLoginLayout = new javax.swing.GroupLayout(PanelLogin);
        PanelLogin.setLayout(PanelLoginLayout);
        PanelLoginLayout.setHorizontalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(SelecAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(SelectEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLoginLayout.createSequentialGroup()
                                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLoginLayout.createSequentialGroup()
                                        .addGap(267, 267, 267)
                                        .addComponent(LoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelLoginLayout.createSequentialGroup()
                                        .addGap(258, 258, 258)
                                        .addComponent(loginContra, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLoginLayout.createSequentialGroup()
                                .addComponent(TxtEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)))
                        .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BarraTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelLoginLayout.createSequentialGroup()
                                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ContraIngresada, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UsuarioIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(IniciarSesion))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLoginLayout.createSequentialGroup()
                                .addComponent(butSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(136, 136, 136)))))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        PanelLoginLayout.setVerticalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectEmpleado)
                    .addComponent(SelecAdmin))
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LoginUsuario)
                            .addComponent(UsuarioIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loginContra)
                            .addComponent(ContraIngresada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(IniciarSesion)))
                .addGap(28, 28, 28)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BarraTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(butSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelIngresarDatos.setToolTipText("");
        PanelIngresarDatos.setAutoscrolls(true);

        NoPlaca.setText("Placa:");

        jLabel1.setText("Tipo");

        FormatoTiempo.add(ButFlat);
        ButFlat.setText("Plano");
        ButFlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButFlatActionPerformed(evt);
            }
        });

        FormatoTiempo.add(ButVariable);
        ButVariable.setText("Variable");
        ButVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButVariableActionPerformed(evt);
            }
        });

        BuscarDbPlaca.setText("Verificar");
        BuscarDbPlaca.setActionCommand("");
        BuscarDbPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarDbPlacaActionPerformed(evt);
            }
        });

        aviso.setText(" ");

        TxtTiempoI.setText("Tiempo");

        TiempoVariable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TiempoVariableMouseClicked(evt);
            }
        });
        TiempoVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiempoVariableActionPerformed(evt);
            }
        });
        TiempoVariable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TiempoVariableKeyTyped(evt);
            }
        });

        generarImpresion.setText("Ticket");
        generarImpresion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarImpresionActionPerformed(evt);
            }
        });

        grupoTipoAutoingresado.add(autoautoingresado);
        autoautoingresado.setText("auto");
        autoautoingresado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoautoingresadoActionPerformed(evt);
            }
        });

        grupoTipoAutoingresado.add(motoautoingresado);
        motoautoingresado.setText("moto");
        motoautoingresado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motoautoingresadoActionPerformed(evt);
            }
        });

        Pago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta" }));
        Pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagoActionPerformed(evt);
            }
        });

        txtpago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtpago.setText(" Ingrese ");

        BilleteIngresado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BilleteIngresadoActionPerformed(evt);
            }
        });

        PuestoBuscandoPlaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESTUDIANTE", "CATEDRATICO" }));
        PuestoBuscandoPlaca.setToolTipText("");
        PuestoBuscandoPlaca.setEnabled(false);
        PuestoBuscandoPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuestoBuscandoPlacaActionPerformed(evt);
            }
        });

        PanelReingreso.setText("REINGRESO");
        PanelReingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelReingresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelIngresarDatosLayout = new javax.swing.GroupLayout(PanelIngresarDatos);
        PanelIngresarDatos.setLayout(PanelIngresarDatosLayout);
        PanelIngresarDatosLayout.setHorizontalGroup(
            PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(ButFlat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ButVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                                        .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                                                .addComponent(NoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(ingresaPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(BuscarDbPlaca))
                                            .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                                                .addGap(120, 120, 120)
                                                .addComponent(generarImpresion)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PanelReingreso))
                                    .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(BilleteIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                                        .addComponent(TxtTiempoI, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TiempoVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(98, Short.MAX_VALUE))
                            .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                                                .addComponent(autoautoingresado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(motoautoingresado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE))
                                            .addComponent(aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIngresarDatosLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PuestoBuscandoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(148, 148, 148))))))
                    .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                        .addComponent(txtpago, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PanelIngresarDatosLayout.setVerticalGroup(
            PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresaPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarDbPlaca)
                    .addComponent(PanelReingreso))
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(autoautoingresado)
                            .addComponent(motoautoingresado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PuestoBuscandoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButFlat)
                    .addComponent(ButVariable))
                .addGap(29, 29, 29)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtTiempoI)
                    .addComponent(TiempoVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpago)
                    .addComponent(Pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BilleteIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(generarImpresion)
                .addGap(328, 328, 328))
        );

        NombreIngresar.setText("Nombre:");

        CarnetIngresar.setText("Carnet:");

        PlacaIngresar.setText("Placa:");

        ButtonGroupIngresar.add(ButMoto);
        ButMoto.setText("Motocicleta");
        ButMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButMotoActionPerformed(evt);
            }
        });

        ButtonGroupIngresar.add(ButAuto);
        ButAuto.setText("Automovil");

        AgregarNuevoUsuario.setText("Guardar");
        AgregarNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarNuevoUsuarioActionPerformed(evt);
            }
        });

        Puesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESTUDIANTE", "CATEDRATICO" }));
        Puesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuestoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpanelAñadirUsuarioLayout = new javax.swing.GroupLayout(JpanelAñadirUsuario);
        JpanelAñadirUsuario.setLayout(JpanelAñadirUsuarioLayout);
        JpanelAñadirUsuarioLayout.setHorizontalGroup(
            JpanelAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelAñadirUsuarioLayout.createSequentialGroup()
                .addGroup(JpanelAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelAñadirUsuarioLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(ButAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpanelAñadirUsuarioLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(AgregarNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpanelAñadirUsuarioLayout.createSequentialGroup()
                        .addGroup(JpanelAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpanelAñadirUsuarioLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(JpanelAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CarnetIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PlacaIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelAñadirUsuarioLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(NombreIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(JpanelAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IngresarNombre)
                            .addComponent(IngresarCarnet)
                            .addComponent(IngresarPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        JpanelAñadirUsuarioLayout.setVerticalGroup(
            JpanelAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelAñadirUsuarioLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(JpanelAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreIngresar)
                    .addComponent(IngresarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(JpanelAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IngresarCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CarnetIngresar))
                .addGap(17, 17, 17)
                .addGroup(JpanelAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlacaIngresar)
                    .addComponent(IngresarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(JpanelAñadirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButMoto)
                    .addComponent(ButAuto)
                    .addComponent(Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AgregarNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        buttRegresar.setText("REGRESAR");
        buttRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttRegresarActionPerformed(evt);
            }
        });

        TxtReingreso.setText("Reingreso");

        Reingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReingresoActionPerformed(evt);
            }
        });

        ButReingreso.setText("Reingreso");
        ButReingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButReingresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelREINGRESOLayout = new javax.swing.GroupLayout(PanelREINGRESO);
        PanelREINGRESO.setLayout(PanelREINGRESOLayout);
        PanelREINGRESOLayout.setHorizontalGroup(
            PanelREINGRESOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelREINGRESOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TxtReingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Reingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelREINGRESOLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButReingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        PanelREINGRESOLayout.setVerticalGroup(
            PanelREINGRESOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelREINGRESOLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(PanelREINGRESOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtReingreso)
                    .addComponent(Reingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ButReingreso)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelFuncionesLayout = new javax.swing.GroupLayout(PanelFunciones);
        PanelFunciones.setLayout(PanelFuncionesLayout);
        PanelFuncionesLayout.setHorizontalGroup(
            PanelFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFuncionesLayout.createSequentialGroup()
                .addGroup(PanelFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFuncionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(PanelIngresarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFuncionesLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(JpanelAñadirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PanelREINGRESO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        PanelFuncionesLayout.setVerticalGroup(
            PanelFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFuncionesLayout.createSequentialGroup()
                .addGroup(PanelFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFuncionesLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(PanelIngresarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFuncionesLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(buttRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PanelFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFuncionesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(JpanelAñadirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFuncionesLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(PanelREINGRESO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pestañas.addTab("Ingreso", PanelFunciones);

        SalidaTickeID.setText("Ingrese ticket Id");

        BuscarTIckeID.setText("Buscar");
        BuscarTIckeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarTIckeIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(SalidaTickeID, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RecibirTickeid, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BuscarTIckeID, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SalidaTickeID)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RecibirTickeid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BuscarTIckeID)))
                .addContainerGap(271, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JpaneSalidaLayout = new javax.swing.GroupLayout(JpaneSalida);
        JpaneSalida.setLayout(JpaneSalidaLayout);
        JpaneSalidaLayout.setHorizontalGroup(
            JpaneSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpaneSalidaLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        JpaneSalidaLayout.setVerticalGroup(
            JpaneSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpaneSalidaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(288, Short.MAX_VALUE))
        );

        pestañas.addTab("Salida", JpaneSalida);

        TablaParaVisualizar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Placa", "Area", "Spot", "Entrada", "Salida", "Modo", "Pago", "Tiempo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaParaVisualizar);

        CopiaInfo.setText("Copiar");
        CopiaInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopiaInfoActionPerformed(evt);
            }
        });

        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        MostrarGanancias.setText("jLabel3");

        verT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todo", "Hoy" }));

        buscarw.setText("Buscar");
        buscarw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarwActionPerformed(evt);
            }
        });

        Exportar.setText("Exportar a CSV");
        Exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportarActionPerformed(evt);
            }
        });

        Mapa.setText("Mapa");
        Mapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Mapa)
                    .addComponent(CopiaInfo))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Actualizar)
                        .addGap(18, 18, 18)
                        .addComponent(verT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(busquedayrescatexd, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buscarw)
                        .addGap(34, 34, 34)
                        .addComponent(Exportar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MostrarGanancias, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MostrarGanancias, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(Mapa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CopiaInfo)
                    .addComponent(Actualizar)
                    .addComponent(verT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busquedayrescatexd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarw)
                    .addComponent(Exportar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pestañas.addTab("Ver", jPanel3);

        Seleccionar.setText("Seleccionar Archivo");
        Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarActionPerformed(evt);
            }
        });

        EleccionSubirDatos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Areacsv", "Spotscsv", "Vehiculoscsv", "Historialcsv", " " }));
        EleccionSubirDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EleccionSubirDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(Direccioncsv, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EleccionSubirDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Seleccionar)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Direccioncsv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Seleccionar)
                    .addComponent(EleccionSubirDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(433, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        pestañas.addTab("Cargar", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pestañas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pestañas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pestañas.getAccessibleContext().setAccessibleName("Ingresar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContraIngresadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraIngresadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraIngresadaActionPerformed

    private void IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionActionPerformed

        
        String Usuario=UsuarioIngresado.getText();
        char[] contraseña=ContraIngresada.getPassword();
       
        VerificarContraseña VC=new VerificarContraseña(Usuario,contraseña,PanelFunciones, PanelLogin, UsuarioIngresado, ContraIngresada, IniciarSesion, 
                TxtEspera, BarraTiempo,ButtGrupoLogin,JpanelAñadirUsuario,pestañas);
       
      
        VC.verificar();
        
        
       
    }//GEN-LAST:event_IniciarSesionActionPerformed

    private void butSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butSalirMouseClicked
      ImageIcon icono= new ImageIcon(getClass().getResource("/Imagenes/Salir.jpg"));
        butSalir.addActionListener((ActionEvent e)->{
            
         int opcion=JOptionPane.showConfirmDialog(this,"Esta seguro de salir?","Salir",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, icono);
            if(opcion!=1){
            
            System.exit(0);
        }
                   
            
        });
        
        
        
    }//GEN-LAST:event_butSalirMouseClicked
    
    private void ButMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButMotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButMotoActionPerformed

    private void AgregarNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarNuevoUsuarioActionPerformed
     
        //obteniendo datos
       String Nombre=IngresarNombre.getText();
       long Carnet=Long.parseLong(IngresarCarnet.getText());
       String Placa=IngresarPlaca.getText().toUpperCase(); 
      String Tipo;
       if(ButAuto.isSelected()){
          
          Tipo="automovil";
      } else{
           Tipo="moto";
           
       }
       
       String area="";
       
       if(Puesto.getSelectedItem().equals("CATEDRATICO")){
           
           area="CATEDRATICO";
           
       }else if(Puesto.getSelectedItem().equals("ESTUDIANTE")){
           
           
           area="ESTUDIANTE";
       }else{
           JOptionPane.showMessageDialog(null,"Ingrese un cargo","CAMPO VACIO",JOptionPane.INFORMATION_MESSAGE);
           
       }
       
         //accion al seleccionar guradar
         
         
         Vehiculo V=new Vehiculo(Placa,Tipo,area);  
         
         Usuario us=new Usuario(0,Nombre,Carnet,V);  
           
        UsuarioDB agg= new UsuarioDB();
        
        agg.AgregarDb(us,V);
        
   
        
        ingresaPlaca.setText(V.getPlaca());
        IngresarNombre.setText("");
        IngresarCarnet.setText("");
        IngresarPlaca.setText("");
          JpanelAñadirUsuario.setVisible(false);
            PanelIngresarDatos.setVisible(true);
            
            Vehiculo Encontrado=agg.BuscarPorPlaca(ingresaPlaca.getText());
            if(Encontrado!=null){
             
             aviso.setText("Usuario encontrado Prosiga");
              String modelo = Encontrado.getTipo();
         
         
         
        if(modelo.equalsIgnoreCase("automovil")){
            
           autoautoingresado.setSelected(true);
            
        }else if(modelo.equalsIgnoreCase("moto")){
            
            motoautoingresado.setSelected(true);
        }}else{
             
            JpanelAñadirUsuario.setVisible(true);
            PanelIngresarDatos.setVisible(false);
             JOptionPane.showMessageDialog(null,"Usuario no Hallado","INGRESE USUARIO",JOptionPane.INFORMATION_MESSAGE);
         }


    }//GEN-LAST:event_AgregarNuevoUsuarioActionPerformed

    private void ButFlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButFlatActionPerformed

        TxtTiempoI.setVisible(false);
         TiempoVariable.setVisible(false);
        Pago.setVisible(true);
        txtpago.setVisible(true);
        BilleteIngresado.setVisible(true);
        
    }//GEN-LAST:event_ButFlatActionPerformed

    private void BuscarDbPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarDbPlacaActionPerformed
        
        
        
      UsuarioDB us = new UsuarioDB();
Vehiculo Encontrado = us.BuscarPorPlaca(ingresaPlaca.getText());

if (Encontrado != null) {

    aviso.setText("Usuario encontrado Prosiga");
    
   
    String modelo = Encontrado.getTipo();
    if (modelo.equalsIgnoreCase("automovil")) {
        autoautoingresado.setSelected(true);
    } else if (modelo.equalsIgnoreCase("moto")) {
        motoautoingresado.setSelected(true);
    }
    
    
    if (Encontrado.getPuesto() != null) {
        if (Encontrado.getPuesto().equalsIgnoreCase("ESTUDIANTE")) {
            PuestoBuscandoPlaca.setSelectedItem("ESTUDIANTE");
        } else if (Encontrado.getPuesto().equalsIgnoreCase("CATEDRATICO")) {
            PuestoBuscandoPlaca.setSelectedItem("CATEDRATICO");
        }
    }
    
} else {
   
    int respuesta = JOptionPane.showConfirmDialog(
        null, 
        "Usuario no Hallado", 
        "¿DESEA INGRESAR USUARIO?", 
        JOptionPane.YES_NO_OPTION
    );
    
    if (respuesta == JOptionPane.YES_OPTION) {
      
        JpanelAñadirUsuario.setVisible(true);
        PanelIngresarDatos.setVisible(false);
    } else {
     
        aviso.setText("Placa no encontrada. Intente nuevamente.");
        ingresaPlaca.setText(""); 
        ingresaPlaca.requestFocus(); 
    }
}
         
         
      
         
         
         
         
    }//GEN-LAST:event_BuscarDbPlacaActionPerformed

    private void ButVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButVariableActionPerformed
       
        if(ButVariable.isSelected()){
            TxtTiempoI.setVisible(true);
            TiempoVariable.setVisible(true);
        
 
        
        Pago.setVisible(false);
        txtpago.setVisible(false);
        BilleteIngresado.setVisible(false);
            
            
         
         TiempoVariable.setText("FORMATO; hora:minutos; '23':'03'");

        
         
        }
        
        
        
        
    }//GEN-LAST:event_ButVariableActionPerformed

    private void TiempoVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiempoVariableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TiempoVariableActionPerformed

    private void autoautoingresadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoautoingresadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoautoingresadoActionPerformed

    private void motoautoingresadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motoautoingresadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motoautoingresadoActionPerformed

    private void generarImpresionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarImpresionActionPerformed

        String Placa=ingresaPlaca.getText();
        
        
        String vehiculo="";
        if(motoautoingresado.isSelected()){
            
           vehiculo="moto";
            
        }else if(autoautoingresado.isSelected()){
            vehiculo="automovil";
            
        }
      
        
        
        String idarea="";
        if(PuestoBuscandoPlaca.getSelectedItem().equals("CATEDRATICO")){
           
           idarea="CATEDRATICO";
           
       }else if(PuestoBuscandoPlaca.getSelectedItem().equals("ESTUDIANTE")){
           
         
           
           idarea="ESTUDIANTE";
       }
        
      
        String modo="";
        double tiempo=0;
        double pago=0;
        if(ButVariable.isSelected()){
            modo="variable";
            tiempo=Double.parseDouble(TiempoVariable.getText());
        }else if(ButFlat.isSelected()){
            modo="plano";
            pago=Double.parseDouble(BilleteIngresado.getText());
            
        }
        
        
        
        
        
        UsuarioDB us=new UsuarioDB();
          
        us.AsignarSpot(Placa, idarea, modo,pago,vehiculo,tiempo );
        
        
        
        
        
        
        ingresaPlaca.setText("");
     BilleteIngresado.setText("");
    }//GEN-LAST:event_generarImpresionActionPerformed

    private void TiempoVariableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TiempoVariableMouseClicked
    
  
    
    TiempoVariable.setText("");
        
    }//GEN-LAST:event_TiempoVariableMouseClicked

    private void BilleteIngresadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BilleteIngresadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BilleteIngresadoActionPerformed

    private void PagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagoActionPerformed
        if(Pago.getSelectedItem().equals("Efectivo")){
            
         txtpago.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        txtpago.setText("Ingrese Efectivo");
            
    }else if(Pago.getSelectedItem().equals("Tarjeta")){
        
         txtpago.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        txtpago.setText("Ingrese No. de tarjeta");
        
    }
                
                
                
    }//GEN-LAST:event_PagoActionPerformed

    private void PuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PuestoActionPerformed

    private void TiempoVariableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TiempoVariableKeyTyped
   
    

    
    
        
        
        
    }//GEN-LAST:event_TiempoVariableKeyTyped

    private void PuestoBuscandoPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuestoBuscandoPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PuestoBuscandoPlacaActionPerformed

    private void buttRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttRegresarActionPerformed
       
   PanelIngresarDatos.setVisible(true);

   
    JpanelAñadirUsuario.setVisible(false);
    PanelREINGRESO.setVisible(false);

   
    buttRegresar.setEnabled(true);
 
   
      
    }//GEN-LAST:event_buttRegresarActionPerformed

    private void BuscarTIckeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarTIckeIDActionPerformed
      
        
        
       String ID=RecibirTickeid.getText();
        
        
        UsuarioDB us= new UsuarioDB();
        
        us.RegistrarSalida(ID);
        RecibirTickeid.setText("");
    }//GEN-LAST:event_BuscarTIckeIDActionPerformed

    private void PanelReingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelReingresoActionPerformed
    
        
        
         PanelREINGRESO.setVisible(true);
        PanelIngresarDatos.setVisible(false);
        
        
    }//GEN-LAST:event_PanelReingresoActionPerformed

    private void ButReingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButReingresoActionPerformed
       
       String Ticket=Reingreso.getText();
      
        PanelIngresarDatos.setVisible(false);
        
        
        UsuarioDB us= new UsuarioDB();
        us.ReingresoTicket(Ticket);
        Reingreso.setText("");
       
    }//GEN-LAST:event_ButReingresoActionPerformed

    private void ReingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReingresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReingresoActionPerformed

    private void CopiaInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopiaInfoActionPerformed
   
        int fila=TablaParaVisualizar.getSelectedRow();
    int columna= TablaParaVisualizar.getSelectedColumn();

    if(fila !=-1&&columna !=-1){
        Object valor=TablaParaVisualizar.getValueAt(fila, columna);
        StringSelection seleccion = new StringSelection(valor.toString());
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(seleccion,null);
        JOptionPane.showMessageDialog(null,"Celda copiada: " + valor);
    }else{
        JOptionPane.showMessageDialog(null,"Seleccione una celda antes de copiar.");
    }

    }//GEN-LAST:event_CopiaInfoActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
       
        UsuarioDB us=new UsuarioDB();
       String sql="";
        if(verT.getSelectedItem().equals("Hoy")){
           sql="SELECT * FROM Ticket WHERE substr(FechaIngreso, 1, 10) =date('now','localtime')";
        }else if(verT.getSelectedItem().equals("Todo")){
            
       sql="SELECT *FROM Ticket";
            
        }
        
 
        
        
        us.datosEnTabla(TablaParaVisualizar,sql);
         MostrarGanancias.setText(us.DatosDeldia());
    }//GEN-LAST:event_ActualizarActionPerformed

    private void SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarActionPerformed
        JFileChooser Ventana= new JFileChooser();
        LeerYGuardarCSV file= new LeerYGuardarCSV(Ventana,Direccioncsv);
        
       switch(EleccionSubirDatos.getSelectedIndex()){
        
           case 0: {
               file.ObtenerDireccion(0);
               break;}
           case 1: {
               file.ObtenerDireccion(1);
               break;}
           case 2:{               
               file.ObtenerDireccion(2);
               
               break;}
           case 3:{
               file.ObtenerDireccion(3);
               break;
           }
    }
        
        
        
    }//GEN-LAST:event_SeleccionarActionPerformed

    private void EleccionSubirDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EleccionSubirDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EleccionSubirDatosActionPerformed

    private void buscarwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarwActionPerformed
  
        
        
       String Buscado= busquedayrescatexd.getText();
        UsuarioDB us=new UsuarioDB();
        us.buscarPorTicket(Buscado,TablaParaVisualizar);
        
        
    }//GEN-LAST:event_buscarwActionPerformed

    private void ExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportarActionPerformed
         
        JFileChooser almacenarD= new JFileChooser();
       almacenarD.setDialogTitle("Selecciona la carpeta donde guardar el archivo");
    almacenarD.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); // solo carpetas
    almacenarD.setAcceptAllFileFilterUsed(false);

    int seleccion=almacenarD.showOpenDialog(null);

    if(seleccion==JFileChooser.APPROVE_OPTION){
        File carpeta=almacenarD.getSelectedFile();

        
        String nombreArchivo="tickets_" + System.currentTimeMillis() +".csv";
        String dir=carpeta.getAbsolutePath() + File.separator+nombreArchivo;

        
        exportar ex=new exportar();
        ex.ticket(dir);

        JOptionPane.showMessageDialog(null,"Archivo exportado correctamente en:\n"+dir,"Exportación exitosa",JOptionPane.INFORMATION_MESSAGE);

    } else {
        JOptionPane.showMessageDialog(null,"Exportación cancelada.");
    }

       

    }//GEN-LAST:event_ExportarActionPerformed

    private void MapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MapaActionPerformed
        
        
         SwingUtilities.invokeLater(() -> new VistaMapa());
        
    }//GEN-LAST:event_MapaActionPerformed

    private void butSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butSalirActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        
        java.awt.EventQueue.invokeLater(() -> new visualizarContenido().setVisible(true));
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton AgregarNuevoUsuario;
    private javax.swing.JProgressBar BarraTiempo;
    private javax.swing.JTextField BilleteIngresado;
    private javax.swing.JButton BuscarDbPlaca;
    private javax.swing.JButton BuscarTIckeID;
    private javax.swing.JRadioButton ButAuto;
    private javax.swing.JRadioButton ButFlat;
    private javax.swing.ButtonGroup ButGroupFunciones;
    private javax.swing.JRadioButton ButMoto;
    private javax.swing.JButton ButReingreso;
    private javax.swing.JRadioButton ButVariable;
    private javax.swing.ButtonGroup ButonGroupOpciones;
    private javax.swing.ButtonGroup ButtGrupoLogin;
    private javax.swing.ButtonGroup ButtonGroupIngresar;
    private javax.swing.JLabel CarnetIngresar;
    private javax.swing.JPasswordField ContraIngresada;
    private javax.swing.JButton CopiaInfo;
    private javax.swing.JTextField Direccioncsv;
    private javax.swing.JComboBox<String> EleccionSubirDatos;
    private javax.swing.JButton Exportar;
    private javax.swing.ButtonGroup FormatoTiempo;
    private javax.swing.JTextField IngresarCarnet;
    private javax.swing.JTextField IngresarNombre;
    private javax.swing.JTextField IngresarPlaca;
    private javax.swing.JButton IniciarSesion;
    private javax.swing.JPanel JpaneSalida;
    private javax.swing.JPanel JpanelAñadirUsuario;
    private javax.swing.JLabel LoginUsuario;
    private javax.swing.JButton Mapa;
    private javax.swing.JLabel MostrarGanancias;
    private javax.swing.JLabel NoPlaca;
    private javax.swing.JLabel NombreIngresar;
    private javax.swing.JComboBox<String> Pago;
    private javax.swing.JPanel PanelFunciones;
    private javax.swing.JPanel PanelIngresarDatos;
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JPanel PanelREINGRESO;
    private javax.swing.JButton PanelReingreso;
    private javax.swing.JLabel PlacaIngresar;
    private javax.swing.JComboBox<String> Puesto;
    private javax.swing.JComboBox<String> PuestoBuscandoPlaca;
    private javax.swing.JTextField RecibirTickeid;
    private javax.swing.JTextField Reingreso;
    private javax.swing.JLabel SalidaTickeID;
    private javax.swing.JRadioButton SelecAdmin;
    private javax.swing.JButton Seleccionar;
    private javax.swing.JRadioButton SelectEmpleado;
    private javax.swing.JTable TablaParaVisualizar;
    private javax.swing.JTextField TiempoVariable;
    private javax.swing.JLabel TxtEspera;
    private javax.swing.JLabel TxtReingreso;
    private javax.swing.JLabel TxtTiempoI;
    private javax.swing.JTextField UsuarioIngresado;
    private javax.swing.JRadioButton autoautoingresado;
    private javax.swing.JLabel aviso;
    private javax.swing.JLabel bienvenida;
    private javax.swing.JButton buscarw;
    private javax.swing.JTextField busquedayrescatexd;
    private javax.swing.JButton butSalir;
    private javax.swing.JButton buttRegresar;
    private javax.swing.JButton generarImpresion;
    private javax.swing.ButtonGroup grupoTipoAutoingresado;
    private javax.swing.JTextField ingresaPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loginContra;
    private javax.swing.JRadioButton motoautoingresado;
    private javax.swing.JTabbedPane pestañas;
    private javax.swing.JLabel txtpago;
    private javax.swing.JComboBox<String> verT;
    // End of variables declaration//GEN-END:variables
}
