/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.estacionamientoproyecto;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author dxnie
 */
public class visualizarContenido extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(visualizarContenido.class.getName());

    /**
     * Creates new form visualizarContenido
     */
    public visualizarContenido() {
        initComponents();
    PanelLogin.setVisible(true);
    PanelFunciones.setVisible(false);
    PanelIngresarDatos.setVisible(false);
          TxtEspera.setVisible(false);
          BarraTiempo.setVisible(false);
          
         setSize(850,630);
         setResizable(false);
         
          setLocationRelativeTo(null);
          // --- CENTRAR PANEL ---
centrarPanel(PanelLogin);
centrarPanel(PanelFunciones);
centrarPanel(PanelIngresarDatos);

// Recentrar al redimensionar la ventana
addComponentListener(new java.awt.event.ComponentAdapter() {
    @Override
    public void componentResized(java.awt.event.ComponentEvent evt) {
        centrarPanel(PanelLogin);
    centrarPanel(PanelFunciones);
    centrarPanel(PanelIngresarDatos);
    }
});
    }

    
    
    
    
    
    
    
    private void centrarPanel(JPanel panel) {
    int x = (getWidth() - panel.getWidth()) / 2;
    int y = (getHeight() - panel.getHeight()) / 2;
    panel.setLocation(x, y);
}
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtGrupoLogin = new javax.swing.ButtonGroup();
        ButtonGroupIngresar = new javax.swing.ButtonGroup();
        ButGroupFunciones = new javax.swing.ButtonGroup();
        PanelLogin = new javax.swing.JPanel();
        bienvenida = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SelecAdmin = new javax.swing.JRadioButton();
        SelectEmpleado = new javax.swing.JRadioButton();
        LoginUsuario = new javax.swing.JLabel();
        UsuarioIngresado = new javax.swing.JTextField();
        loginContra = new javax.swing.JLabel();
        ContraIngresada = new javax.swing.JPasswordField();
        IniciarSesion = new javax.swing.JButton();
        TxtEspera = new javax.swing.JLabel();
        BarraTiempo = new javax.swing.JProgressBar();
        butSalir = new javax.swing.JButton();
        PanelFunciones = new javax.swing.JPanel();
        ButIngresar = new javax.swing.JToggleButton();
        ButDisponibilidad = new javax.swing.JToggleButton();
        ButEliminar = new javax.swing.JToggleButton();
        ButModificar = new javax.swing.JToggleButton();
        ButFinancias = new javax.swing.JToggleButton();
        PanelIngresarDatos = new javax.swing.JPanel();
        TxtNombre = new javax.swing.JLabel();
        IngresarNombre = new javax.swing.JTextField();
        NoPlaca = new javax.swing.JLabel();
        ingresaPlaca = new javax.swing.JTextField();
        ModeloCarro = new javax.swing.JLabel();
        IngresarModelo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        ButAuto = new javax.swing.JRadioButton();
        ButMoto = new javax.swing.JRadioButton();
        PanelBuscar = new javax.swing.JPanel();
        TxtBuscar = new javax.swing.JLabel();
        BuscarXPlaca = new javax.swing.JLabel();
        BuscarPlaca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        bienvenida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenida.setText("Bienvenido");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Inicie sesión:");

        ButtGrupoLogin.add(SelecAdmin);
        SelecAdmin.setText("Administrador");

        ButtGrupoLogin.add(SelectEmpleado);
        SelectEmpleado.setText("Empleado");

        LoginUsuario.setText("Usuario:");

        loginContra.setText("Contraseña:");

        ContraIngresada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraIngresadaActionPerformed(evt);
            }
        });

        IniciarSesion.setText("Iniciar sesion");
        IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionActionPerformed(evt);
            }
        });

        TxtEspera.setText("TIempo de espera :");
        TxtEspera.setName(""); // NOI18N

        butSalir.setText("Salir");
        butSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelLoginLayout = new javax.swing.GroupLayout(PanelLogin);
        PanelLogin.setLayout(PanelLoginLayout);
        PanelLoginLayout.setHorizontalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(SelecAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(SelectEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLoginLayout.createSequentialGroup()
                                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLoginLayout.createSequentialGroup()
                                        .addGap(277, 277, 277)
                                        .addComponent(LoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelLoginLayout.createSequentialGroup()
                                        .addGap(268, 268, 268)
                                        .addComponent(loginContra, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLoginLayout.createSequentialGroup()
                                .addComponent(TxtEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)))
                        .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BarraTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelLoginLayout.createSequentialGroup()
                                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ContraIngresada, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UsuarioIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(IniciarSesion))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLoginLayout.createSequentialGroup()
                                .addComponent(butSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(136, 136, 136)))))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        PanelLoginLayout.setVerticalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectEmpleado)
                    .addComponent(SelecAdmin))
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LoginUsuario)
                            .addComponent(UsuarioIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loginContra)
                            .addComponent(ContraIngresada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(IniciarSesion)))
                .addGap(28, 28, 28)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BarraTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(butSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        ButGroupFunciones.add(ButIngresar);
        ButIngresar.setText("Ingresar");
        ButIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButIngresarActionPerformed(evt);
            }
        });

        ButGroupFunciones.add(ButDisponibilidad);
        ButDisponibilidad.setText("Disponibilidad");
        ButDisponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButDisponibilidadActionPerformed(evt);
            }
        });

        ButGroupFunciones.add(ButEliminar);
        ButEliminar.setText("Eliminar");
        ButEliminar.setAutoscrolls(true);

        ButGroupFunciones.add(ButModificar);
        ButModificar.setText("Modificar");
        ButModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButModificarActionPerformed(evt);
            }
        });

        ButGroupFunciones.add(ButFinancias);
        ButFinancias.setText("Financias");

        PanelIngresarDatos.setAutoscrolls(true);

        TxtNombre.setText("Nombre:");

        NoPlaca.setText("Placa:");

        ModeloCarro.setText("Modelo:");

        jLabel1.setText("Tiempo");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 hora", "2 horas", "3 horas", "4 horas", "5 horas", "6 horas", "7 horas", "8 horas", "9 horas", "10 horas", "11 horas", "12 horas" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        ButtonGroupIngresar.add(ButAuto);
        ButAuto.setText("Automovil");

        ButtonGroupIngresar.add(ButMoto);
        ButMoto.setText("Motocicleta");
        ButMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButMotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelIngresarDatosLayout = new javax.swing.GroupLayout(PanelIngresarDatos);
        PanelIngresarDatos.setLayout(PanelIngresarDatosLayout);
        PanelIngresarDatosLayout.setHorizontalGroup(
            PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModeloCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NoPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IngresarNombre)
                    .addComponent(ingresaPlaca)
                    .addComponent(IngresarModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                        .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                                .addComponent(ButAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addContainerGap(568, Short.MAX_VALUE))
        );
        PanelIngresarDatosLayout.setVerticalGroup(
            PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIngresarDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IngresarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ingresaPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModeloCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IngresarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButAuto)
                    .addComponent(ButMoto))
                .addContainerGap(275, Short.MAX_VALUE))
        );

        TxtBuscar.setText("Buscar ");

        BuscarXPlaca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BuscarXPlaca.setText("Ingrese Placa");

        BuscarPlaca.setToolTipText("");

        TablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Placa", "Modelo", "Tiempo", "Tipo de  vehiculo"
            }
        ));
        jScrollPane1.setViewportView(TablaClientes);

        javax.swing.GroupLayout PanelBuscarLayout = new javax.swing.GroupLayout(PanelBuscar);
        PanelBuscar.setLayout(PanelBuscarLayout);
        PanelBuscarLayout.setHorizontalGroup(
            PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuscarLayout.createSequentialGroup()
                .addGroup(PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBuscarLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(TxtBuscar))
                    .addGroup(PanelBuscarLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(BuscarXPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BuscarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelBuscarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelBuscarLayout.setVerticalGroup(
            PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuscarLayout.createSequentialGroup()
                .addComponent(TxtBuscar)
                .addGap(18, 18, 18)
                .addGroup(PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarXPlaca)
                    .addComponent(BuscarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelFuncionesLayout = new javax.swing.GroupLayout(PanelFunciones);
        PanelFunciones.setLayout(PanelFuncionesLayout);
        PanelFuncionesLayout.setHorizontalGroup(
            PanelFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFuncionesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(PanelFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelIngresarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(PanelBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelFuncionesLayout.createSequentialGroup()
                            .addComponent(ButIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(ButDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(ButEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(ButModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(49, 49, 49)
                            .addComponent(ButFinancias, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        PanelFuncionesLayout.setVerticalGroup(
            PanelFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFuncionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButIngresar)
                    .addComponent(ButDisponibilidad)
                    .addComponent(ButEliminar)
                    .addComponent(ButModificar)
                    .addComponent(ButFinancias))
                .addGap(52, 52, 52)
                .addComponent(PanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(PanelIngresarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(PanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(PanelFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(PanelFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContraIngresadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraIngresadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraIngresadaActionPerformed

    private void IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionActionPerformed

       

        
        
        
        
        String Usuario=UsuarioIngresado.getText();
        char[] contraseña=ContraIngresada.getPassword();
       
        VerificarContraseña VC=new VerificarContraseña(Usuario,contraseña,PanelFunciones, PanelLogin, UsuarioIngresado, ContraIngresada, IniciarSesion, TxtEspera, BarraTiempo,ButtGrupoLogin);
       
      
        VC.verificar();
        
       
    }//GEN-LAST:event_IniciarSesionActionPerformed

    private void butSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butSalirMouseClicked
      ImageIcon icono= new ImageIcon(getClass().getResource("/Imagenes/Salir.jpg"));
        butSalir.addActionListener((ActionEvent e)->{
            
         int opcion=JOptionPane.showConfirmDialog(this,"Esta seguro de salir?","Salir",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, icono);
            if(opcion!=1){
            
            System.exit(0);
        }
            
            
            
            
            
        });
        
        
        
    }//GEN-LAST:event_butSalirMouseClicked

    private void ButModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButModificarActionPerformed
        
        
        ButModificar.addActionListener((ActionEvent k)->{
        
           if( ButModificar.isSelected()){
               PanelIngresarDatos.setVisible(true);
               PanelBuscar.setVisible(false);
               
           }
        
    });
    }//GEN-LAST:event_ButModificarActionPerformed

    private void ButDisponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButDisponibilidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButDisponibilidadActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void ButIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButIngresarActionPerformed
        
        
        ButIngresar.addActionListener((ActionEvent s)->{
        
        PanelBuscar.setVisible(ButIngresar.isSelected());
        
        });
        
        
        
        
        
        
    }//GEN-LAST:event_ButIngresarActionPerformed

    private void ButMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButMotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButMotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        
        java.awt.EventQueue.invokeLater(() -> new visualizarContenido().setVisible(true));
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar BarraTiempo;
    private javax.swing.JTextField BuscarPlaca;
    private javax.swing.JLabel BuscarXPlaca;
    private javax.swing.JRadioButton ButAuto;
    private javax.swing.JToggleButton ButDisponibilidad;
    private javax.swing.JToggleButton ButEliminar;
    private javax.swing.JToggleButton ButFinancias;
    private javax.swing.ButtonGroup ButGroupFunciones;
    private javax.swing.JToggleButton ButIngresar;
    private javax.swing.JToggleButton ButModificar;
    private javax.swing.JRadioButton ButMoto;
    private javax.swing.ButtonGroup ButtGrupoLogin;
    private javax.swing.ButtonGroup ButtonGroupIngresar;
    private javax.swing.JPasswordField ContraIngresada;
    private javax.swing.JTextField IngresarModelo;
    private javax.swing.JTextField IngresarNombre;
    private javax.swing.JButton IniciarSesion;
    private javax.swing.JLabel LoginUsuario;
    private javax.swing.JLabel ModeloCarro;
    private javax.swing.JLabel NoPlaca;
    private javax.swing.JPanel PanelBuscar;
    private javax.swing.JPanel PanelFunciones;
    private javax.swing.JPanel PanelIngresarDatos;
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JRadioButton SelecAdmin;
    private javax.swing.JRadioButton SelectEmpleado;
    private javax.swing.JTable TablaClientes;
    private javax.swing.JLabel TxtBuscar;
    private javax.swing.JLabel TxtEspera;
    private javax.swing.JLabel TxtNombre;
    private javax.swing.JTextField UsuarioIngresado;
    private javax.swing.JLabel bienvenida;
    private javax.swing.JButton butSalir;
    private javax.swing.JTextField ingresaPlaca;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loginContra;
    // End of variables declaration//GEN-END:variables
}
